apiVersion: v1
kind: Secret
metadata:
  name: xr-onboarding-verify-attack-test
  namespace: app-xr-onboarding-verify-cicd
stringData:
  test: "this should be rejected by the idp-onboarding AppProject's namespaceResourceWhitelist"
