apiVersion: catalog.idp.io/v1alpha1
kind: NodeJSApplication
metadata:
  name: cicd-redirect-verify
  namespace: app-cicd-redirect-verify-cicd
spec:
  nodeVersion: "20"
  packageManager: npm
  port: 8080
  visibility: private
